### ISSUE TITLE
Update pools query to only return/search/scan enabled chains

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#100]
Problem:
Right now the frontend queries for all chains, and are returning both Rinkeby + Ropsten in production

Candidate Solutions:
A - Improve query to dfpy-sql
B - Setup empty rinkeby/ropsten csvs to clear up records inside of dfpy-sql-db

**Comment by KatunaNorbert** [comment]
I think we shouldn't do that in the web app, as the web should return all the pools from the supported chainIds.
The supported chainIds should be the same in the backend and frontend so if the backend is synchronized(as it is right now, returning only pools from supported main networks) the query on the frontend wouldn't make any difference

**Comment by kremalicious** [comment]
no pools anymore, no querying of test networks happening on production.
