### ISSUE TITLE
Do a first pass to make df-web mobile friendly

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#101]
This is a placeholder ticket.
@idiom-bytes @KatunaNorbert @trizin 

Expand this as we progress so we can do an update in the future.
- [ ] On mobile, the beta text overlap with the header

**Comment by trentmc** [comment]
Most large holders of OCEAN won't be holding it in their mobile wallets. Therefore priority of this would be lower

And, it's high effort to do this.

Therefore, it's low bang/buck for "make DFWeb Mobile Friendly". I recommend removing from planning.

**Comment by trentmc** [comment]
Closing. Way bigger fish to fry
