### ISSUE TITLE
Pool explorer: help user know what "TVL" and "Volume" columns mean

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#105]
**Motivation**

Questions that users may ask:
- What units are TVL and volume in? Eg OCEAN, H2O, USD, other?
- Does TVL include the value of datatoken, or basetoken+datatoken?
- What is "volume"?
- Over what time interval is volume? Eg the last day, the last week, since counting started for the current round, or lifetime for the asset?

Right now Pool Explorer doesn't answer these.

**Suggested solution**

- Put "$" text to the left "TVL" text
- Put "$" text to the left "Volume" text
- Have a tooltip (tiny "?" next to the column label) to the right of "TVL" text. When mouse hovers above, it says "Total value locked in basetoken (OCEAN, etc) for this pool, in units of USD"
- Have a tooltip to the right of "Volume" text. When mouse hovers above, it says "Data consume volume for this pool, in units of USD, since the start of this DF round". I'm assuming that ", since the start of this DF round" is the interval you're showing, if it's something else, then revise text accordingly (or don't show that part)

**Comment by KatunaNorbert** [comment]
TVL and Volume are returned in OCEAN(base token). Regarding your proposed solution, should we transform into USD and put the '$' text to the left or put OCEAN to the right?
I would keep it in base token as that is what values are represented in other places across the app

**Comment by trentmc** [comment]
> Inside the CSVs the value is in basetoken, 

To be clear, you're reading from poolinfo-chainx.csv, right?

It's gonna be pretty easy to add another column into that, something like vol_amt_USD.

And that will keep the info flow much cleaner.

I could create an issue for df-py to do this; then do it.

Would that work for you?

**Comment by trentmc** [comment]
In [this PR](https://github.com/oceanprotocol/df-py/pull/207), I moved the to-usd calculations out of calcrewards.py, to a new module tousd.py. It helps me in my work on [df-py-206](https://github.com/oceanprotocol/df-py/issues/206) but will also be helpful here.

**Comment by trentmc** [comment]
> It might be better to just fetch the USD rates in the frontend, and display it.

This is error prone. It took a lot of testing and fiddling to have something reliable, and to test that it's reliable.

Why create 2x the effort?

> We probably want to have tousd.js created as well.

Why create 2x the effort?

> The backend may not want to have this information because it needs to be looked up live

It's already calculated early in the flow. 

It makes far more sense to reuse the df-py stuff, rather than 2x effort for building & maintenance of redundant functionality in JS.

I'll build support for this in df-py in the next 24h, and report back here.

**Comment by trentmc** [comment]
> I'll build support for this in df-py in the next 24h, and report back here. df-py#210

OK, I've completed this. It's merged into df-py main branch.

Now, there are two new columns in poolinfo-chainx.csv:
- `vol_amt_USD`
- `stake_amt_USD`

I've updated the [example csvs slide](https://docs.google.com/presentation/d/11Nu_emSgw3iYZKDcmnvZC_aOM00MDyYTtTWQP4PYox4/edit#slide=id.g11be0d94c8d_0_0) and [data flow slide](https://docs.google.com/presentation/d/11Nu_emSgw3iYZKDcmnvZC_aOM00MDyYTtTWQP4PYox4/edit#slide=id.p) accordingly.

Back to you, @KatunaNorbert :)
