### ISSUE TITLE
Cannot stake - Approve button is disabled

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/df-web#118]
Approve button is disabled. This is the error on the console.

![Screenshot_20220617_022038](https://user-images.githubusercontent.com/25263018/174193814-1c196cba-2e4c-408d-a9a0-ce536b838b67.png)

**Comment by KatunaNorbert** [comment]
I haven't managed to recreate this bug, @trizin let me know if this insists, otherwise I'm going to close this issue
