### ISSUE TITLE
User is unable to claim rewards in Metamask from other browsers

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#141]
Bug:
User has earned rewards, clicks the claim button, but receives an error.
"Failed to claim Data Farming rewards!"
https://t.me/Farm_Ocean/174556

Wallet: Metamask
Browser(device): safari (iOS)

**Comment by trentmc** [comment]
Was the problem due to Polygon RPC being down?

If yes, let's close.

If no, what's the status?

**Comment by KatunaNorbert** [comment]
I asked yesterday inside the telegram channel to check If there are still any issues but haven't received any response.
Today a dispensed some rewards and successfully claimed, so I assume this was an RPC issue.

In conclusion, I'm going to close this issue.

**Comment by KatunaNorbert** [comment]
User responded he is still getting the issue, so I reopen this and debug using mobile(Safari) with Metamask combination

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/141?planning-poker) with Zenhub @KatunaNorbert

**Comment by idiom-bytes** [comment]
I don't think this is an issue anymore.
