### ISSUE TITLE
Expand UX/UI to support claiming passive rewards

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#206]
Users will be able to earn rewards in 3 ways:
![download (40).png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/b6655bca-4889-4d15-a568-8258e42780a2)

Right now, our FE supports the last implementation. These rewards will be distributed via the following streams:
```
Reward #1 => OPC Revenues => FeeDistributor.vy
Reward #2-A => DF Rewards => FeeDistributor.vy
Reward #2-B => DF Rewards => DFRewards.sol
```

Right now, our UX/UI has been developed to support all requirements for Rewards #2-B.
Support for Reward#1 & Reward#2-A still needs to be developed via the front end.

### Build a claim portal for additional rewards inside FeeDistributor.vy
- [x] Update FE to show the estimated rewards that are coming through the FeeDistributor.vy contract
- [x] Implement FE + contract integration logic that enables users to claim rewards via the FeeDistributor.vy contract
- [x] Update Claim Portal to include a summary fo all rewards inside of DFRewards.sol + FeeDistributor.vy
- [x] Each claims interface should display it's own rewards (i.e. DFRewards vs. FeeDistributor rewards)

Note: There will be no way to distinguish OPC rewards from 50% of DF rewards. These numbers will be blended together as-is.

**Comment by KatunaNorbert** [comment]
Why can't we just add a method to the veFeeDistributor contract to return the claimable amount?

**Comment by idiom-bytes** [comment]
Continued the work on here
https://github.com/oceanprotocol/df-web/pull/223

**Comment by idiom-bytes** [comment]
DF Rewards
- Got nan problem when calculating rewards, to create rewardsperlp-OCEAN.csv
- Created a manual rewardsperlp-OCEAN.csv file
- Fixed problems and ran the csv through the dispense function so I could dispense to contract successfully
- TODO: Finish visualizing + claiming rewards

VE Rewards:
- Tried to manually distribute according to PR => https://github.com/oceanprotocol/df-py/pull/286/files
- Added functionality to dispense passive rewards => https://github.com/oceanprotocol/df-py/pull/271
- Getting crashes/problems when trying to run 
```
fee_distributor.checkpoint_token()
fee_distributor.checkpoint_total_supply()
```

**Comment by idiom-bytes** [comment]
Viewing rewards & claiming them is now working.
- I was able to dispense rewards via DFRewards & FeeDistributor
- I was able to see rewards available to claim on dashboards/rinkeby
- I was able to claim various rewards

However, ther eare some issues:
1. FeeDistributor.vy logs an Event that gives you more info WRT claiming rewards. Please see df-py #294
1. veFeeEstimate calculates the user has a balance, but user is unable to claim it. Finishing connecting all conditions to the UI.

**Comment by idiom-bytes** [comment]
I think this is mostly completed. Can we verify and close the issue?

**Comment by idiom-bytes** [comment]
I think this is mostly completed. Can we verify and close the issue?

**Comment by idiom-bytes** [comment]
Closing this issue.
PR is here => https://github.com/oceanprotocol/df-web/issues/248
Remaining issues are here => https://github.com/oceanprotocol/df-web/issues/247
