### ISSUE TITLE
Rinkeby - Success popups & gas limit calculations

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#208]
Couple of issues hindering UX atm:
Locking veOcean -"success popup" - Success logic is triggered before transaction completes successfully. The tx can end up failing.

Locking veOcean Failin TXs - Gas limit calculations (not sure if it's rinkeby related) is returning an extremely high value, causing the tx to fail. You can adjust the gas limit, the "lock ocean" tx (rather than accept) still fails. Brownie calculates around 400k gas as required to succeed in the transaction. The current calculation is returning an estimate in the 100m's.

**Comment by KatunaNorbert** [comment]
This is fixed inside: https://github.com/oceanprotocol/df-web/pull/205.  by setting a custom gas limit value
