### ISSUE TITLE
veFeeDistributor rewards - Implement calculations required to provide user with information on claimable rewards

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#210]
CRV veFeeDistributor rewards are calculated inside the contract and may require a lot of RPC calls.

Let's identify how CRV is handling this, and make sure we're able to provide a similar solution. The current concern is there may be a lot of internal data in the contract it relies on, and there is no simple way of getting at this.

In parallel: 
+ ask curve.fi & lobsterdao for insights. someone there might be able to share their info on how this is implemented for CRV
+ Start a thread with the team so we can agree on the direction.

Candidate Solution A: Expand FeeDistributor.vy to include a view claimable function
Candidate Solution B: Write a smartcontract that has only one view function(reads data from veOcean & veFee and does the math). This avoids touching the original contracts
Candidate Solution C: Do it via RPC in the backend
+ could do it on the backend side, db, calculate it once per week and have it solved in dfsql
+ would not have to do it every time when the user opens the web page

### DoD:
- [ ] Implement [calculations from veFeeDistributor](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veFeeDistributor.vy#L229-L293) into FE

**Comment by alexcos20** [comment]
WIP in https://github.com/oceanprotocol/df-py/pull/283

**Comment by idiom-bytes** [comment]
Fee calculation has been integrated here.
https://github.com/oceanprotocol/df-web/pull/223

![Screenshot from 2022-09-12 22-35-34.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/6c70a218-2d48-4264-90b6-07fa912921f2)

**Comment by idiom-bytes** [comment]
Candidate C has been implemented.

Addressing individual issues more granularly and moving this to completed.
