### ISSUE TITLE
Verify that locking w/ 0 tokens is disabled, and users are unable 

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#211]
Idiom was able to get a lock w/ 0 ocean.
Let's review this flow and make sure that all users end up w/ a lock that is correct.

[Unknown Considerations]
- There might be additional use cases we're not considering, such as you create a lock and someone else desposits for you.
- Is there a reason why we should support this in the FE?

**Comment by KatunaNorbert** [comment]
Verified and could not lock with 0 oceans.
There was a bug related to locking and multiplier&voting power calculation when the lock was done on Thursday and I fixed it inside https://github.com/oceanprotocol/df-web/pull/152

**Comment by idiom-bytes** [comment]
Yeah, I verified this as well. Closing issue.
