### ISSUE TITLE
Improve GQL/API queries and optimize them further

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#226]
Low priority for now, unless there are clear problems with diminishing performance.
There might be other optimizations to do, however the initial requirements have been delivered.

We are hitting vols API to get dataNFTs each time we're opening the data explorer age. We may be able to improve this by listening for events/caching queries, and optimizing this further.

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
