### ISSUE TITLE
Claiming VE Rewards - FeeDistributor.vy & FeeEstimator.vy - Everything points to user being able to claim, but is unable to do so

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#247]
### Problem Description
Everything is pointing to the user being able to claim, the user has never claimed before, but is unable to do so either from the UI or calling the contracts directly.

Account in question => 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260
PR w/ changes => https://github.com/oceanprotocol/df-web/pull/249

Image 1
- FeeEstimator is reporting that the user is in epoch 0, and there are amounts to be claimed.
- The FE is reflecting these values
- The user in this instance has tried to claim the rewards, has succeeded, but their balance remains the same (225.62026 OCEAN)

![Screenshot from 2022-09-21 17-54-33.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/ee52830b-335a-4278-8bf6-3b4beb0ef8c1)

Image 2
- FeeEstimator in brownie is confirming the user has amounts to claim
- Transaction completed successfully
https://rinkeby.etherscan.io/tx/0x68e990b1cec4268df1365b2a4469f04c3cabd48d714ecd6fc9646be9ae965666
- User balance did not move, and FeeEstimator.vy still reports there is an amount to claim
- User epoch and value does not move after tx completes successfully

![Screenshot from 2022-09-21 17-56-07.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/1c95797f-79f7-4907-a66d-992f644608a6)

### DoD:
- [ ] Contract/calculations reports amount that the user is able to claim
- [ ] User is able to correctly claim rewards as reported

**Comment by idiom-bytes** [comment]
PR that includes all changes
https://github.com/oceanprotocol/df-web/pull/249

**Comment by alexcos20** [comment]
I do wonder how are you sending your transactions

this one worked just fine:  https://rinkeby.etherscan.io/tx/0xcf009fb06308f802ea2c9c6b79207be5a92b76e28ab37fb511f09571bbcd0605

I claimed for you

**Comment by idiom-bytes** [comment]
Like this
https://github.com/oceanprotocol/df-web/blob/acc8737090d3576af6e9af1687eb68d57b3948ff/src/utils/feeDistributor.js#L41

**Comment by idiom-bytes** [comment]
Here are more examples of me working through it via my local ganache, app running.

I'm able to claim a partial ammount from 100 wei, leaving me a remainder of 32 wei that i'm unable to claim, no matter how much I try to move the chain ahead.

![Screenshot from 2022-09-29 14-47-10.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/93aa6776-f34c-4a3a-90cf-63dc52575a1a)

In the front end:
- I have a reward to claim
- I go through the process
![Screenshot from 2022-09-29 14-42-53.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/15b004f4-04a8-47bf-8748-fbc3c0f35b2eI)

I call the contract, sign the transaction, and receive a successful tx/claim just like in brownie.
However, 32 wei remains left over.
![Screenshot from 2022-09-29 14-43-17.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/a1079bb0-0391-4000-a536-d3a31c09130b)

**Comment by idiom-bytes** [comment]
Here are more examples of me working through it via my local ganache, app running.

I'm able to claim a partial ammount from 100 wei, leaving me a remainder of 32 wei that i'm unable to claim, no matter how much I try to move the chain ahead.

![Screenshot from 2022-09-29 14-47-10.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/93aa6776-f34c-4a3a-90cf-63dc52575a1a)

In the front end:
- I have a reward to claim
- I go through the process
![Screenshot from 2022-09-29 14-42-53.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/15b004f4-04a8-47bf-8748-fbc3c0f35b2eI)

I call the contract, sign the transaction, and receive a successful tx/claim just like in brownie.
However, 32 wei remains left over.
![Screenshot from 2022-09-29 14-43-17.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/a1079bb0-0391-4000-a536-d3a31c09130b)

**Comment by idiom-bytes** [comment]
@trizin @alexcos20 I am continuously running into this issue in local ganache.

I'm getting all the right amounts from contract, and am able to claim from contract, but the contract does not allow me to claim the full amount.

I have assigned this to you to get help.

**Comment by alexcos20** [comment]
By looking at your transaction:   https://rinkeby.etherscan.io/vmtrace?txhash=0x68e990b1cec4268df1365b2a4469f04c3cabd48d714ecd6fc9646be9ae965666&type=gethtrace2

last call is
```
{
      "type": "STATICCALL",
      "from": "0xb99baa8d5b131c9140be2f13ea6d2494df272919",
      "to": "0x57cd87bb197b74df44fd69177c0550b9a0c04619",
      "gas": "0xc77b",
      "gasUsed": "0x970",
      "input": "0x28d09d47000000000000000000000000e2dd09d719da89e5a3d0f2549c7e24566e9472600000000000000000000000000000000000000000000000000000000000000001",
      "output": "0x0000000000000000000000000000000000000000000000000f41c16e39bd9a3100000000000000000000000000000000000000000000000000000049d482455d00000000000000000000000000000000000000000000000000000000631ba89b0000000000000000000000000000000000000000000000000000000000ad385c"
    }
    ```
    
    which in code is https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veFeeEstimate.vy#L123
```
user_point: Point = VotingEscrow(ve).user_point_history(addr, user_epoch)
```

(keccak of   user_point_history(address,uint256)  = 28d09d475b63d4f35d73169e2ee0302e4f01cf20dc7f18862e9a68090b7429c5

So args of this call are:
 - 0xe2DD09d719Da89e5a3D0F2549c7E24566e947260  (address)
 - 1  (epoch)         
 
 PS: Now your epoch is 2, so something changed in the mean time

Result is:
```
0x0000000000000000000000000000000000000000000000000f41c16e39bd9a3100000000000000000000000000000000000000000000000000000049d482455d00000000000000000000000000000000000000000000000000000000631ba89b0000000000000000000000000000000000000000000000000000000000ad385c
```
which corresponds to:
```
[ user_point_history(address,uint256) method Response ]
  bias   int128 :  1099372463214402097
  slope   int128 :  317097919837
  ts   uint256 :  1662757019
  blk   uint256 :  11352156
  ```

So, ts is 1662757019   (Fri Sep 09 2022 20:56:59 GMT+0000)

You tx failed probably at https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veFeeEstimate.vy#L128-L129
```
if week_cursor >= _last_token_time:
        return 0
```

Unfortunately, I cannot know the value of last_token_time at the point in time, but I believe that you were missing some checkpoint calls

**Comment by alexcos20** [comment]
Try to call "TOGGLE_ALLOW_CHECKPOINT_TOKEN"  and allow everyone to checkpoint_token  and see how it goes

**Comment by idiom-bytes** [comment]
Thanks for the help everyone.
https://github.com/oceanprotocol/barge/pull/328
