### ISSUE TITLE
~4years button exceeds by 1 week the max unlock time

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#257]
To reproduce, current day Friday 23 Sept, max lock end date set to 24 Sept 2026

**Comment by EnzoVezzaro** [comment]
My account seems to work fine, I just wonder if the amount values are right though; the max it goes is 99%, is that right?

<img width="488" alt="Screenshot 2022-09-23 at 07 58 33" src="https://user-images.githubusercontent.com/13741335/191955463-1644ce1e-b7a0-4730-86c4-6dd2d4a25a17.png">

**Comment by KatunaNorbert** [comment]
It should be 24th, the lock end date it's always rounded to Thursday by the contract, so other days should be disabled on the frontend to not create confusion. I'm not sure how you managed to get Wednesday

**Comment by EnzoVezzaro** [comment]
It's acting weird actually. I think I found what you mean.

This is what happens with a new wallet:
 it's 1 week off as you said, but the `4 years` button actually gets the correct date
https://user-images.githubusercontent.com/13741335/191959358-36c23521-6730-400c-9591-d9e5ff364641.mp4

This is what happens with a wallet already used:
it's 1 week off, but the other way 😅
https://user-images.githubusercontent.com/13741335/191959859-9c4c32f0-26a4-47c7-a122-38fa9f2d08e6.mp4

**Comment by idiom-bytes** [comment]
Refactored and fixed => https://github.com/oceanprotocol/df-web/pull/272
