### ISSUE TITLE
users can transact with amount 0

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/df-web#260]
**Describe the bug**
Users can initiate a transaction with 0 as value. Naturally, the tx fails throwing a big error on screen.

I'd expect the button to be disabled if the value it's 0.

https://user-images.githubusercontent.com/13741335/191961122-00a27c82-9429-4eba-af4d-1fcb7080ea50.mp4

**Comment by KatunaNorbert** [comment]
That's not actually a bug, you can only update the lock end period without locking more tokens
