### ISSUE TITLE
tx fails after locking for 4 years

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/df-web#261]
**Describe the bug**
After locking my oceans for 4 years, I tried to lock more Oceans for the next week, but the tx failed. 

**Expected behavior**
If we can't change the date, the button should be disabled on the `Lock date` and show a message for the user.

**Screenshots**

https://user-images.githubusercontent.com/13741335/191964650-52b01e61-7bfb-442e-ae10-e675cf80d755.mp4

NOTE: issue related to amount `0` is reported in issue #260

**Comment by KatunaNorbert** [comment]
Handled inside #272

**Comment by idiom-bytes** [comment]
Refactored and fixed => https://github.com/oceanprotocol/df-web/pull/272
