### ISSUE TITLE
Expand metrics in veOcean summary card

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#286]
Add some more metrics to the veOcean summary card
- Added num users, but reverted it. Let's focus on more applicable metrics.

### DoD
- [ ] average lock duration

**Comment by AnaLoznianu** [comment]
I suggest we add the number of users/accounts that locked oceans and are hodlers.

**Comment by idiom-bytes** [comment]
We discussed this metric and decided to not put this in for a variety of reasons.
Primarly, it's not very actionable.
