### ISSUE TITLE
Date format on calendar view

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#295]
It works on @KatunaNorbert machine... but on mine it looks different.
The date format should be consistent everywhere, and hopefully in the DD-MM-YYYY format.

![Screenshot from 2022-09-27 10-14-34.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/1ee534e9-b935-4a37-8fcf-8cae65a7e793)

**Comment by trentmc** [comment]
Closing. Super-old issue. Way bigger fish to fry
