### ISSUE TITLE
Allocation UX - Update table to show extra fields & improve search

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#297]
Right now @KatunaNorbert experienced some issues with allocating on ganache
Please give it another try and let's double check that this is working

What seems to be working:
- Getting the total allocated amount
- Allocating to one datanft

What seems to be breaking:
- Allocating to multiple datanfts

[DT Symbol + Network + View Button]
Perhaps roll it all into 1 Item:
- clickable ahref => marketplace
- network icon to the left side of "DT Symbol"
Column Title: Data Token
Item Name: datatoken.symbol
Item URL: datatoken.marketplace url
Item Network Icon: chainIcons[datatoken.chainid]

### DoD:
- [x] Show networks as icons
- [x] Fix the lower case datanft (not displayed by default - use hashed)
- [x] Have the DID available to use (not displayed by default)

**Comment by kremalicious** [comment]
From personal experience, the presented data in the table prevents any UX flow from even starting and I would assume lots of people drop off as it is just too cumbersome to find assets and allocate:

1. Finding a dataset on Ocean Market and want to stake in it.
2. Taking the DID, and on df-web search for it.
3. Nothing shows up.
4. Trying to search for datatoken name.
5. Nothing shows up.
6. Searching for title.
7. Nothing shows up.
8. Searching for "Energy Web Chain"
9. Nothing shows up.
10. Searching for the NFT address.
11. Nothing shows up.
12. Finding my dataset after going through 7 pages.
13. Have to click 10 times(!) to get 100% allocated.

So you force me to go through every table row one-by-one as they can't be differentiated, the search only works per page, but not across the table. So a complete UX nightmare to find assets. 

As an absolute quick minimum please add actual unique data to the table to be able to differentiate rows, and then make the search work through the whole table.

All in all this is not feasible to work with, and I have 7 pages of that:

<img width="1048" alt="Screen Shot 2022-09-30 at 13 00 58" src="https://user-images.githubusercontent.com/90316/193265094-02fa5743-963a-4c28-9ba0-ff79239edfcf.png">

More UX:

- please let me type a number in the allocation field so stop forcing people to click like crazy
- Everything has 0 volume too which is simply not true as some assets were sold in last days, remove volume if all numbers are wrong

**Comment by idiom-bytes** [comment]
Hi @kremalicious thanks a ton for your feedback. For metrics that we're tracking, showing onto the table, and what we're hoping to improve I have been adding to this ticket (likely to be broken down into multiple epics) => https://github.com/oceanprotocol/df-py/issues/280


Critical:
- 2 items start with 10% but the user has 100% left to allocate, so the user can assign 120% which will result in a problem
- List items by DT.symbol() so we can more easily see what's going on

There are other critical improvements we need to do (i.e. make list bigger than 20 items) and I have created smaller tickets to resolve/ship them.

Further Improvements:
- Use network icon rather than full network name
- If the user doesn't have any allocations, order by TotalAllocated, Volume. This should always show valid items.
- If the user has allocations, order by My Allocations, Total Allocated, Volume. This should always show what the user has first.

**Comment by idiom-bytes** [comment]
I think we're trying to do multiple things here and it may not be the way forward.

I propose we try to separate the data feed we get from dfsql + dfpy + our data pipelines... from the Allocate panel and make it more explicit. Users, are also getting these functionalities mixed, and we're going to have to play gymnastics with data that we get from the DB.

By keeping this separate, we can continue to expand the table with more "panes/tabs". We can then, more clearly show users how they are distributing their veOCEAN across these assets but feel there isn't enough feedback/information about it.

Even if we cache locally, if you add 15.3 veOCEAN to 123k, you won't see anything.

![Screenshot from 2022-09-30 13-31-46.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/e93e15c0-8048-48e8-a6f5-652104e02a4b)

**Comment by idiom-bytes** [comment]
I'm just wondering if it might help to make these two things a bit more distinct somehow, whether through styling or not, might be useful. Further, users are changing their % but they don't really see any more information about their veOCEAN and how it's getting distributed.

I'm wondering if it might make sense to style the table differently and structure the data in such a way that makes it obvious what the "Data Farming" part is vs. the data that we get from our dfsql/apis.

Even if we cache locally, many users will put in 1% into 135k Ocean and have no visual feedback or indicator of what's going on. I'm ok with that, but feel we need to provide better feedback, such as a more visual way of indicating you 

![Screenshot from 2022-09-30 13-31-46.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/49d24bd4-90e1-42ec-999f-a5674e9bd914)
