### ISSUE TITLE
Lock VeOcean - Provide preview for changes to date & amount

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#298]
When trying to expand the lock, it would be good to provide them with an accurate estimate of what they will get, including adjustments to any of their existing rewards. When I locked 17 ocean for 1 month, I got something like 0.5veOCEAN. Balance and allocation power are the same. If I decide to put in 1k OCEAN for 4 years, this means I get 1k veOcean. But the 17 I added, will be updated for the 4 years. Will I get the voting power for 1000 + 17, or 1000 + 0.5?

Example:
User changes from 1 week => 3 months

Cand A: “New Estimated veOCEAN” shows below the date picker, recalculating based on existing lock. 
Cand B: Left Panel updates showing user’s new end dates, bonuses, etc…

**Comment by trentmc** [comment]
Closing. Super-old issue. Way bigger fish to fry
