### ISSUE TITLE
Update veOCEAN allocated after completing tx

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#299]
```Not sure if the total allocation is failing to update or if I have misunderstood something? I allocated 50% of my locked VeOcean to an asset but it still says that the total amount locked is 0? < Solution: Anything that requires 5+ minutes should be cached locally until it can be updated.```
- User expects to see veOCEAN balances reflected against assets
- Data for veOCEAN allocated comes from our backend and is updated every 5 minutes

Candidate Solutions
- calculate and update veOCEAN balances and cache locally until it updates
- reorganize elements and order to make the allocating UX more obvious for users
- leave it as is, there are several steps the user must do in order to complete their allocation, including signing several transactions

### DoD:
- [ ] Explain table and how often it gets updated.
- [ ] Calculate and cache veOcean amounts allocated until fetched again

**Comment by idiom-bytes** [comment]
Additionally, how to improve Data Explorer:

Candidate Solution A:
1. Move all allocation related elements to right
2. Move all column/dfsql elements to the left
3. Make more room for dfsql data + explain somewhere that this is the data that updates every 5 minutes
4. Change styling for objects on right, especially "My Allocation". This works with the datasets, but it does not update the data from dfsql.

Even if we cache it locally and modify those values, there could be 1 million veOCAN in a data asset and the user would not be able to tell how much (percent) they have allocated to the asset. By changing the styling of the "My Allocation" column, we can visibily communicate how the user is allocating their veOCEAN. 

Candidate Solution B:
- Create a separate column that shows "MyVeOCEAN vs. Global veOCAN" (I believe this is rendundant.

![Screenshot from 2022-09-29 14-12-02.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/67586bf9-843b-4b4f-9ff0-0260ef8938c7)

**Comment by trentmc** [comment]
This issue is super-old. It's either fix, or not a priority at all. So, closing.
