### ISSUE TITLE
Enable user to adjust allocations by 1% or by entering the amount

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#302]
### DoD:
- [ ] Change allocation step from 10% => 1%
- [ ] Enable users to type in the allocation they want

**Comment by kremalicious** [comment]
So you then force everyone to click 100(!) times if they want 100% allocated? Please rather concentrate on allowing users to type in numbers as described in #297

**Comment by idiom-bytes** [comment]
I agree, however the step needs to be more granular and flexible.
I also agree with your feedback => ```please let me type a number in the allocation field so stop forcing people to click like crazy```

**Comment by idiom-bytes** [comment]
@KatunaNorbert i believe this is completed, can you please close the ticket?
