### ISSUE TITLE
Implement delegation

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#303]
There are other designs we've looked at (CVX), let's design a component and implement it.

### DoD:
- [x] Design/Dev delegation component
- [x] User is able to delegate veOCEAN and get info on it
- [x] Do full E2E test (FE work). Blocked by "E2E test on goerli" issue

**Comment by trentmc** [comment]
Not happening, afaik. There's already psdnOCEAN.

**Comment by idiom-bytes** [comment]
```Not happening, afaik. There's already psdnOCEAN.```
They are not the same.

Using this task to represent the implementation part (vs. the design part)
