### ISSUE TITLE
Voting period is vague

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/df-web#311]
As a user on the "Data Explorer" screen there are only vague timeframes mentioned, making it impossible to know when to start or reassign allocations to maximize rewards:

> ...starting from Thursday, as soon as Data Farming goes live.

What Thursday? Which time? Which timezone? "as soon as Data Farming goes live", so when is that?

Please simply tell users when voting periods starts and ends on this screen. Example Balancer:

<img width="579" alt="Screen Shot 2022-09-30 at 13 40 06" src="https://user-images.githubusercontent.com/90316/193271703-0e36d191-010c-4eaf-b626-9b7071e2d0ec.png">

**Comment by idiom-bytes** [comment]
Tooltips will be expanded as part of issue 293 - https://github.com/oceanprotocol/df-web/issues/293
Improving the voting period....
![Screenshot from 2022-10-11 14-21-42](https://user-images.githubusercontent.com/69865342/195180459-bf276156-7170-45ca-b846-ff0b75e801d5.png)

**Comment by kremalicious** [comment]
Adding more words does not make it more clear. Instead of "Data Farming Epoch 5" & "Ends in" just say "Voting period ends in ...". No need for tooltips then.

I do not know what the above screenshot refers too. This is what I see on live right now, which is less descriptive than what was there when I opened up this issue:

<img width="641" alt="Screen Shot 2022-10-12 at 13 56 22" src="https://user-images.githubusercontent.com/90316/195348322-d1333d63-bff7-428b-99be-bf962603c78b.png">

Would suggest getting consistent in how this period is called. So far we use "allocating", "voting", "round", "epoch". They are all the same so stick to only 1 term, on all screens

**Comment by idiom-bytes** [comment]
Every blog has referred to it as "Round" so I updated it to that.

The screenshot above refers to the PR attached to this ticket...
