### ISSUE TITLE
Estimate gas giving huge numbers

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/df-web#338]
Looking at some of the last transactions (https://etherscan.io/address/0xe86bf3b0d3a20444de7c78932ace6e5effe92379), I saw that our gas estimate is > 3 mil.    When the actual consume is about 1/10th of that.

Example:
type:  create_lock
tx: https://etherscan.io/tx/0x32f6d54fcd6924c6b35a8b6fd1a171353f72a6ddca67cf5977865aea24a24471
estimated:  3,617,061 
actual usage: 334,805 (9.26%)

Example2:
type: increase_unlock_time
tx: https://etherscan.io/tx/0xae61b958e730656f1c5d2f749dec1b715e64ab3f6a7f316d8b3440d480b11ca1
estimated: 2,930,241 
actual usage: 271,145 (9.25%)

This really breaks the UI, because users will think that they will spend 70$ to lock tokens, when the actual value is 7$

**Comment by kremalicious** [comment]
happening on everything, also allocations, which users are told cost around 20 EUR when gas fees are low:

<img width="356" alt="Screen Shot 2022-10-17 at 12 27 53" src="https://user-images.githubusercontent.com/90316/196165761-a5890c66-8032-4674-9965-f89514d47cb2.png">
