### ISSUE TITLE
Pool explorer: “liquidity as USD” columns

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#36]
**What**
Pool explorer gets _two_ new columns:
- "liquidity (USD)" - total liquidity of all LPs (for that pool)
-  "my liquidity (USD)" - liquidity of the user (for that pool)

**Motivation**

Having liquidity also expressed in USD is helpful, because then the user can compare apples-to-apples for pools with OCEAN liquidity vs H2O liquidity. (And other potential pools in the future).

**TODOs**

- [ ] Ask someone in BE to build support from BE
- [ ] Implement in FE

**Comment by kremalicious** [comment]
no pools anymore
