### ISSUE TITLE
Replace WalletConnect from unpkg (June 2023)

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#369]
We currently get WalletConnectProvider from unpkg which is based on an api call. This is not ideal because if the api is down we can't use WalletConnect.
We should find a different way, ideally an npm package to get the WalletConnectProvider.

**Comment by idiom-bytes** [comment]
There has been a bit of back and forth, whether we can remove or keep the package. We need to continue research and consider what needs to be done here so we can complete this and move on.
- Based on the initial issue/pr, there have been improvements via cleanup and sorting out dependencies. We however do not have a long term solution for WalletConnect.
- If WC is down, there isn't much we can do.

We're going to time block this, move to the med-term backlog, and see if we can come back to this in the future.

**Comment by kremalicious** [comment]
1st step:

Add and import @walletconnect/web3-provider from your local resources, however that works in Svelte to restore current app ASAP

Second step:

Do not spend any more time on the deprecated walletconnect version and upgrade to v2, making @walletconnect/web3-provider obsolete. Kick out all you have for connecting web3 and start fresh from here, using the default web3modal. Then style it a bit to your liking. Done  https://docs.walletconnect.com/2.0/web3modal/html-js/installation

**Comment by idiom-bytes** [comment]
We're basically waiting for an update from WC and trying to complete the issue due the QR code not working. This is one of the few PRs remaining.
