### ISSUE TITLE
Pool explorer: “Reward Function” column - FE & BE

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#37]
**What**
Pool explorer gets a new column: "reward function"

**Motivations**

Helps the user to discover pools (via browse, search, filter) according to how well they do on reward function. This will help them in staking decisions.

**TODOs**

- [x] BE build support. See [df-py#97](https://github.com/oceanprotocol/df-py/issues/97)
- [ ] Implement in FE

**Comment by idiom-bytes** [comment]
@trentmc didn't see my name on this until now. will revisit asap after completing deployment

**Comment by idiom-bytes** [comment]
I propose we separate the FE task from the BE task, so we can complete this and do the remainder after.

**Comment by kremalicious** [comment]
No pools anymore. This should be weekly volume as described in #268
