### ISSUE TITLE
No allocation possible in Firefox

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/df-web#370]
Not possible to do anything in Firefox with those number input. Editing existing one makes it disabled without updating _Available allocation_. Every other field is disabled by default. Not possible to do any allocations with Firefox:

![test](https://user-images.githubusercontent.com/90316/199462304-28023645-fcee-4a4a-a298-a03891efb870.gif)

**Comment by kremalicious** [comment]
workaround is to NOT use arrow buttons, but only manually type the number

**Comment by KatunaNorbert** [comment]
@kremalicious thanks for reporting this.
The intention was indeed to hide the arrows.

**Comment by idiom-bytes** [comment]
We have a solution for global space, we will continue to try to solve for local components, if unable to, we'll update this globally for now.

**Comment by kremalicious** [comment]
still pretty funky on current live:

![test](https://user-images.githubusercontent.com/90316/200300569-7f1dcf1c-e58d-445e-a178-a32267eefb61.gif)

So would be great to communicate ANYWHERE how deployments work and when. Issue being closed as completed for 2 hours but no fix rollout to actual users is continuing to confuse.

**Comment by kremalicious** [comment]
24 hours later and it is mysteriously deployed so closing
