### ISSUE TITLE
Split data explorer into different views so users can understand aggregate vs. epoch data

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#372]
Problem: There are multiple views of data farming that may bring intuition to users
Example: When users lock up their allocation, they are expecting to see the number move by a lot but it moves by very little (this is because as time passes, more allocation will get sampled, and the total increases) vs. a live/total aggregate amount.

I.E. I lock up 500k veOCEAN and only see a 20k veOCEAN change

Candidate Solution A: Split the data explorer into multiple views
- live data (total consume, total veOCEAN)
- epoch data (week's consume, week's veOCEAN allocated)

Further improvements:
- historical metrics
- apy per data nft

### DoD:
- [ ] User is able to see multiple views of live vs. epoch metrics and understand how they are being calculated

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/372?planning-poker) with Zenhub @KatunaNorbert

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
