### ISSUE TITLE
Update UX to support re-allocating away from datasets from purgatory

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#374]
### Problem:
- Right now assets in purgatory cannot be shown, enabling the user to simply reallocate
- Use the latest route from df-py to show purgatory assets that need to be re-allocated
- Disable "Reset Allocation" button

### DoD:
- [ ] User is able to see items in purgatory that still contain allocations
- [ ] Purgatory datasets look visibly different from the rest, cannot be interacted with, and can only have allocation removed from it
- [ ] User is able to rebalance allocations away from purgatory datasets
- [ ] User is able to update allocations, away from purgatory, with a single tx

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/374?planning-poker) with Zenhub @KatunaNorbert

**Comment by KatunaNorbert** [comment]
Handled here: #442
