### ISSUE TITLE
FE: Historical Rewards - Active & Passive Rewards

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#375]
### Problem:
- Right now users are unable to verify their historical active or passive rewards
- Right now we're not calculating historical passive rewards (these are calculated via the contract)
- Right now we are calculating historical active rewards, but are not visualizing them in the app (the are calculated via the df-py pipeline)

### DoD:
- [ ] Use rewards route to grep user's historical rewards per epoch
- [ ] Show in rewards page user's historical passive and active rewards

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/375?planning-poker) with Zenhub @KatunaNorbert

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
