### ISSUE TITLE
z-depth visible - data farming top bar may need a bg-color

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#390]
Minor issue. Not urgent. Do not prioritize/start.

![Screenshot from 2022-11-15 10-45-27.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/1fcec68d-8c17-48a5-b405-6a6d8e41a911)

**Comment by trentmc** [comment]
Closing. Way bigger fish to fry
