### ISSUE TITLE
Handle no epoch config for current DF round

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#404]
We have an object with all past and future DF round configs.
We need to handle the scenario when there is no more config in the future for current round, so we are reminded to add them but then app doesn't crash or show some concerning values.

**Comment by idiom-bytes** [comment]
I originally hoped that df-py would generate more epoch configurations. I have proposed a few other places that could generate the source data.

Until then, we should continue configuring epochs.json

**Comment by idiom-bytes** [comment]
Referred to this problem in [df-issue #114](https://app.zenhub.com/workspaces/ve--df-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-issues/114)
