### ISSUE TITLE
Explore different ways to communicate yield as a function of time

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#416]
### Problem:
Right now, it's difficult for users to get an idea of APY over time, based on the different actions they perform, and relative to other locks that people are creating (i.e. user creates a lock of 1m for 1 week, and that throws other measurements out the window)

Ways to potentially model this:
- Yield as a function of time locked
- Yield as a function of ocean locked
- Yield as a result of average weight

### DoD:
- [ ] Identify potential solutiosn and sign off one of them
- [ ] Implement chart and publish, review if needed

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
