### ISSUE TITLE
Mobile app is not linking or rendering pages correctly

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#417]
Users are trying to use mobile webapp but it doesn't link to different pages correctly

Screenshot of chat
![Screenshot from 2022-11-29 12-01-58.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/a6d9db00-3c01-4a0e-ab4c-a3a1b04917c9)

Video
https://images.zenhubusercontent.com/488111637/6770ffb2-0e2b-4222-83f1-5f305fa4e8d7/rpreplay_final1669567363.mp4

**Comment by KatunaNorbert** [comment]
I'm not sure about this issue, I can't reproduce it, I tested on iPhone and works on all browsers.
