### ISSUE TITLE
Improve page titles, descriptions, and hanging titles that are outside of cards

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#450]
### Problem
1. Many pages do not have clean titles, and descriptions of what each page does
2. The app icon/title on the top left is missing and could use more love
3. The title of the app is long, and a poor description

### General Feedback

Feedback 1 - Change title of app to "Data Farming"  

Feedback 2 - Add a clear title of what the app is on the top left
Inspiration: In [market.oceanprotocol.com](http://market.oceanprotocol.com/) on the left you'll see the Ocean logo and "Ocean Market". Yet current [df.oceandao.org](http://df.oceandao.org/) has just Ocean logo on the left. Clearly name it "Data Farming"  

Feedback 3 - Add titles for each page, describing what it is and what it does.
We could explain df/ve even better yet, and succinctly.
Inspiration: In [market.oceanprotocol.com](http://market.oceanprotocol.com/) main page, front and center it says "Ocean Market: A marketplace to find, publish and trade datasets in the Ocean Network."  

#### Rewards Page:
Title - Data Farming Rewards
Description - "Earn rewards by locking OCEAN and curating data."

Additional Feedback (for Rewards Page):
- drop the hanging Earn Ocean Rewards title
- Move the Data Farming History title into the table

#### Farms Page:
Title - Data Farms
Description - "Allocate veOCEAN to assets and curate data."

#### veOCEAN page: (consider renaming it to Vault)
Title - Vault
Description - "Lock Ocean to receive veOCEAN, access Data Farming, and earn Rewards."

### DoD:
- [ ] Improve webpage tab title
- [ ] Improve webpage title (top left)
- [ ] Improve titles & descriptions for each page
- [ ] Address any hanging cards & titles by implementing the feedback above

**Comment by trentmc** [comment]
A lot of work has been done on this issue since it was created. These days we're ok "ok" shape. Any further work is low priority for the foreesable future. When we want to improve again, it will rear its head readily. 

So, closing.
