### ISSUE TITLE
Update DF Table - Publisher Rewards

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#461]
### DoD:
- [x] Add drop down with 3 filters: all datasets, assets with allocations, my published assets
- [x] Add publisher address + link to marketplace
- [ ] Ready to go. Please finish review & publish.

**Comment by idiom-bytes** [comment]
2 days total, one more day to go.

**Comment by idiom-bytes** [comment]
Reviewed PR, looks great!

**Comment by EnzoVezzaro** [comment]
this is ready to go!
