### ISSUE TITLE
Research & Agree on Analytics Solution

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#465]
Use an external tool to measure different analytics in order to improve user interaction and measure progress in achieving defined goals  

# DoD:
- [ ] Proposals discussed. Meeting on Wednesday. Make decision, sign off, and move forward.

**Comment by EnzoVezzaro** [comment]
what tools are we going to use for this? Web2 based like GAnalitics (🤢), or something in our Web3 world like Dune Analytics?

I read this interesting [blog post](https://www.third.academy/article/the-challenge-with-web3-analytics), it might contain some useful information.

**Comment by KatunaNorbert** [comment]
As also mention in the blog post you shared, web2 and web3 analytics are different segments for now. We can use both and get different analytics.
I was thinking to integrate some web2 based analytics at first, and looks like GAnalytics could be a good starts as it has a free plan.

**Comment by EnzoVezzaro** [comment]
ok, great. Yeah I think GA will be good enough for now, but maybe we can think about something else.

Do we have a list of the exact metrics we need? That would give us a better understanding and maybe find a better tool for our end goal.

**Comment by KatunaNorbert** [comment]
This is a list of main metrics that could be useful, but we can adjust it while we explore the tool, there might be some more specific metrics offered: _**Traffic, Bounce Rate, Conversion Rate, Average session duration, Percentage of returning visitors, Entry pages, Exit pages**_

**Comment by EnzoVezzaro** [comment]
Sounds great. These are some product I found browsing the Web:

- https://umami.is/ (open source)
- https://www.openwebanalytics.com/ (open source PHP composer)
- https://countly.com/ (open source community version)
- https://plausible.io/ (not free/open source)
- https://web3auth.io/ (not free / can be self hosted)

They all seems good options for tracking user's behavior, we might be also able to track some onchain data or aggregate that information into the user's sections.

**Comment by EnzoVezzaro** [comment]
After looking at all the alternatives here, we're still convinced GA is the easiest to configure and setup as it doesn't require infrastructure's maintenance. All the alternatives above require setting up and maintaining a server, which we might not want to do right now. 

There's a bit of work on GA to get it GDPR compliant, but looks easy enough. We might need to find a better solution (as a service, not self-hosted). 

We can also implement Vercel Analytics (even though is limited, it might be useful to have ):
- https://vercel.com/docs/concepts/analytics/audiences/quickstart

**Comment by idiom-bytes** [comment]
Can we pay for a subscription to Plausible and not give the data to GA?

**Comment by KatunaNorbert** [comment]
I can agree with using Plausible as long as we don't choose a self-hosted version and we agree with paying the subscription.
I would choose to pay over dealing with GDPR compliance.

**Comment by EnzoVezzaro** [comment]
I think all depend on what direction we want to go. Do we want to have total control over what we're collecting? then we should go with a self-hosted solution (Like Plausable, Umami, or Countly), which might require some effort from us to setup (in this case I'd suggest Plausable to get quickly to an agreement and start the implementation). 

Otherwise the other option is, again, something like GA which has all the infrastructure figured it out, and might ease the implementation, but all the data will be on a centralized service (which is a NO NO in my opinion). 

I don't see any problem on implementing any of them, but I'd rather having this data on a hosted solution manage by us.

**Comment by idiom-bytes** [comment]
We're going to use Plausible and pay for it.
Daniel is going to help us setup an account.

The other streams will coordinate in the future to solve the individual need.
