### ISSUE TITLE
Identify & fix improperly-used html elements

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#466]
TODO: analyze the HTML code, identify and fix if wrong elements are used inside components

**Comment by EnzoVezzaro** [comment]
Based on what we have in the market our semantics should follow something like this in homepage. I'll try to do the same for all the pages. 

Homepage:
<img width="756" alt="Screenshot 2023-02-21 at 08 25 30" src="https://user-images.githubusercontent.com/13741335/220346933-132d61c7-a831-48bc-b969-1ad13c74297b.png">

**Comment by KatunaNorbert** [comment]
This is already fixed
