### ISSUE TITLE
Check if Wallet Connect 2.0 is ready to go (wait for June)

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#468]
If WC is ready to go complete df-369 (and close 3 points)
Otherwise, close this issue (and close 1 point, do not move DF-369)

If you connect with CB, Kucoin, and other CEXs', it works.
If you connect w/ Metamask/Ledger, it doesn't.

Blockers:
1. Mobile apps are not loading/functioning correctly. Deadline was moved to start of June. Many wallets have not integrated with them. Expect issues until then.
2. From rollups => vite, it's not going to completion. However when we build the app to release, the build fails.

DoD:
- [x] Checked if it's possible. We need to wait.
- [x] Review in June.

**Comment by KatunaNorbert** [comment]
Wallet Connect 2.0 shipped with #369
