### ISSUE TITLE
Create a user storyline for veDelegation

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#476]

**Comment by KatunaNorbert** [comment]
Storyline description:

delegator
-User lands to rewards page and is informed about delegation
-Clicks on a button and it is redirected to delegate screen
-Reads the description of how delegation works
-Introduces the wallet address he wants to delegate to into an input
-Clicks on delegate button and signs the transaction
-Can see the address he delegated to and can remove delegation at any time
-Can extend/update delegation
-Clicks on remove delegation button and signs transactions in order to get back his allocation power

receiver
-can see the received delegation
-can give up on received delegations

Methods:
-create_boost
-adjusted_balance_of
-delegated_boost
-received_boost
-token_cancel_time
-batch_set_delegation_status
-cancel_boost

**Comment by idiom-bytes** [comment]
Hi @KatunaNorbert your description and follow ups with design & work seemed to be clear wrt your storylines/overview of delegation. Can we close this ticket?
