### ISSUE TITLE
GUI won't let me "update lock end date" 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#479]
**Describe the bug**

I locked a bunch of OCEAN into veOCEAN in Oct last year. For 4 years.

I wanted to update the lock end date to 4 years from _now_, it such that I top up my veOCEAN, and therefore max out APY. (The smart contract allows this of course.)

I went to https://df.oceandao.org/veocean, and connected my wallet. It tells me how much OCEAN and veOCEAN I have, good. It lets me fill in fields of how much to lock and how long to lock for, good. 

And there's a big maroon button "UPDATE LOCK END DATE". That's good! That's what I want to end up pressing.

Alas, it's grayed out. No matter what parameters I fiddle with, it remains grayed out.

Which means I can't top-up, and therefore I can't max out my APY.

Exception: I had tried this with several wallets. The first, it actually worked within 5 min fiddling. But no amount of fiddling, browser restarting, wallet reconnecting etc allowed me to do this with other wallets, they all stayed grayed out. 

Something's up.

**Comment by KatunaNorbert** [comment]
@trentmc can you help me with some more details, this looks fine for me using Metamask?
-Which wallet are you using?
-Which browser?
-Did you check the agreement checkbox?

**Comment by trentmc** [comment]
> Which wallet are you using?
> Which browser?
Ubuntu 22, Chrome. Metamask with Trezor underneath.

> Did you check the agreement checkbox?
Yes. Didn't do anything.

**Comment by KatunaNorbert** [comment]
I was trying but I can't reproduce it. 
I'm not sure if it's wallet related but I can't test it with Trezor, maybe someone else can If they use it.

**Comment by trentmc** [comment]
It may be a trezor thing but not likely, because I never got to the point to be able to sign (which is where metamask hands off to trezor).

You can therefore (almost certainly) test with just metamask.

**Comment by KatunaNorbert** [comment]
Managed to reproduce the issue. It appears if you already have a lock, your OCEAN balance is 0 and you try to update the lock. The button shouldn't be disabled if balance is 0 and you try to update.

**Comment by trentmc** [comment]
Note: I've been iterating with Norbert outside of this github issue.

And, he's now got the fix merged. 

I tested. It works. Closing:)
