### ISSUE TITLE
Calculate and display expected APY inside lock screen

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#480]
Calculate the expected APY before user creates a lock, to better understand the APY he can receive after locking, and encourage amount and lock time increase.

**Comment by KatunaNorbert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE-DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/480?planning-poker) with Zenhub @EnzoVezzaro

**Comment by idiom-bytes** [comment]
Let's promote Autobots solution for now and focus on publisher rewards.

Autobots solution can be improved further (i.e. include Active Rewards as part of the calculation) but for now, let's promote and focus on publisher rewards.
