### ISSUE TITLE
Highlight 2x allocations for publishers

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#481]
Inform user visually that he can receive 2x allocation power if he allocates to his own dataset

**Comment by KatunaNorbert** [comment]
Owner allocation it's now visible inside `/nftinfo` on staging

**Comment by EnzoVezzaro** [comment]
@KatunaNorbert why is #494 closing this issue?

**Comment by jamiehewitt15** [comment]
Yeah, I think that was a mistake. #494 closes another bug
