### ISSUE TITLE
Unable to extend lock time: GUI complains "Unlock Date field must be later than 2027-03-18"

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#495]
### Describe the bug

I'm in https://df.oceandao.org/veocean. My wallet holds OCEAN that's been locked for 4 years, until "17-09-2026". I locked it in Sept 2022.

I went to top-up my lock time, to earn more. 

I clicked on "4 years" link to change the lock end date to 4 years from now. 
- It updated the "Lock end date" field to "03/04/2027*. 
- And it gives a red text error message right below, saying "Unlock Date field must be later than 2027-03-18". 
- And the button to "Update lock end date" is grayed out and not clickable (vs magenta and clickable) 
- That's erroneous. I _should_ be able to lock any date later than the current date it's locked for "17-09-2026"
- Yet I can't change the date by clicking "4 years". It complains like above. I think the issue is that " 2027-03-18" is _more_ than 4 years in the future, and it can't handle that. Maybe a rounding error for the week?
- I also tried to change the date by clicking on the calendar icon. A small calendar widget pops up. I click through it, to get to Mar 2027. But all the dates there are gray, and I can't click on them. 
- I also tried to change the date: in the calendar widget, clicking "clear". Then the dates all kinda zeroed out and looked red. They kinda hinted that I could type the value. But, I couldn't.
- I fiddled around some more: in the calendar widget, selecting Feb 2027. From that, I selected a Feb date. Then the Mar 4 date was now clickable via the calendar. So I clicked that. Now, the GUI no longer complains, and I the button to "Update lock end date" is magenta and clickable (good). So, somehow I was able to work around. 
- I also found: when it is causing problems, if I refresh the browser, then it will stop complaining and I can do my thing.

There may be two issues:
- clicking "4 years" sometimes rounds up too far into the future (by an extra week?), and then the rest of the GUI complains
- the calendar widget changes the state of "lock end date" in sometimes unpredictable ways

**Comment by trentmc** [comment]
I gave a lot of info, I'm not sure how much more I can provide.

Perhaps have others try?

**Comment by KatunaNorbert** [comment]
I think it might be something related to lock end date state not being properly updated on some actions, that's why refreshing the page solves it.
@trentmc do you remember what action you made before running into this issue: updating lock end time, switching account etc..?

**Comment by trentmc** [comment]
I just tried to reproduce it. I can't.

My guess: recall that I reported this at the same time as reporting two other bugs. I believe you've fixed those. I'm guessing that those fixes implicitly fixed this one.

So I guess we can close this.

I _did_ discover another issue though. I'll create a new issue right now.
