### ISSUE TITLE
veOCEAN date format is inconsistent: DD-MM-YYYY one place, MM-DD-YYYY another

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#496]
### Description

Go to https://df.oceandao.org/veocean and you'll see something like the following. The dates are where the red arrows are. Note how they're inconsistent:
- date on the left is DD-MM-YYYY
- date on the right is MM-DD-YYYY (it's 4 years from now, in March 2027)

Did you know? One of these is European date format, the other is North American. (Yikes)

### Towards a solution

Rather than just being consistently one or the other (NA or Europe) we can do something that is both (a) consistent and (b) not vague.

Possibilities:
1. YYYY-MM-DD. E.g. 2023-03-27. Goes from big --> small, nice to sort. But, you have
2. YYYY-MonthName-DD. E.g. 2023-Mar-27
3. MonthName-DD-YYYY. E.g. Mar-27-2023
4. DD-MonthName-YYYY. E.g. 27-Mar-2023

Analysis:
- (1) leaves room for confusion (MM <> DD)
- (2) leaves no room for confusion and is a sane order (big -> med -> small)  
- (3) leaves no room for confusion and is how people often think of dates: "March 27, 2023" 
- (4) leaves no room for confusion and is a sane order (small -> med -< big)

(2)(3)(4) are basically tied for best. (1) may cause confusion.

**Comment by EnzoVezzaro** [comment]
Hi @trentmc , something like this works, right?

<img width="756" alt="Screenshot 2023-03-09 at 08 19 30" src="https://user-images.githubusercontent.com/13741335/224021466-c86ed137-6bd5-494d-b9a9-804f88e4e7c4.png">

**Comment by trentmc** [comment]
> Hi @trentmc , something like this works, right?

I just added option (4) in the description above. It's what you suggested.

I also added a brief analysis of all options (1)-(4).

Options (2), (3) or (4) are basically tied for best.

So, your suggestion (4) works!

**Comment by EnzoVezzaro** [comment]
> So, your suggestion (4) works!

great. I'll open a PR for it 👍🏽
