### ISSUE TITLE
Fix user's APY - Needs to combine passive + active correctly

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#502]
### Problem

We need to properly combine passive APY & active APY. We can't just add it. It needs to be sum(passive daily APR, active daily APR), then converted to APY.

![image.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/00acf812-bb6e-430c-8fd1-96f93a016f21)

Note:
- There is already a separate ticket to address the avg Actifve APY

### DoD:
- [ ] User APY should be aggregated correctly

**Comment by KatunaNorbert** [comment]
It is correctly used, it might just be some component rendering issue in your case.
![Screenshot 2023-03-13 at 10.20.10.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/50bdb5ba-72a7-4ab7-8b2a-58598b469c4b)

**Comment by trentmc** [comment]
Norbert confirms that this is now done correctly
