### ISSUE TITLE
Warning: "Connect to Mainnet" - User is in Mainnet

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#503]
### Problem:
- User is inside mainnet
- Warning appears telling user they're in mainnet

### Problem:
- Seems inconsistent
**- Please debug and dissect issue to fix all errors**
- User is connected to ETH, Told to switch to Polygon
![image (1).png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/4e274cc4-006e-4398-955c-40f139914203)

User is in mainnet - Told to connect to mainnet
![Screenshot from 2023-03-09 15-27-18.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/9b60eb69-fcc3-4dd3-a503-1517dbafcdd1)

### DoD:
- [ ] "Connect To Network" message only appears at the right times.

**Comment by jamiehewitt15** [comment]
Has anyone been able to reproduce this bug?
