### ISSUE TITLE
Rename & remove events that we are tracking in Plausible

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/df-web#504]
These are all of the events that we are currently tracking: 

- Link to veOcean page
- Button Sellect max input
- Button Redirect to veOCEAN link
- Button Claim
- Button Update Allocations
- Button Reset Allocations
- Button Get Allocations
- Link to ocean market profile
- Button Token Approval
- Button Close WalletConnect Modal
- Button Metamask Connect
- Button WalletConnect Connect wallet
- Button Switch network
- Button Set allocation to amount
- Button Allocate
- Button X Allocate
- Link to df homepage
- Link to datafarming page
- Link to activerewards page
- Link external to about blog post
- Button Switch Netwrok to...
- Button Connect wallet
- Button Reset to connected account
- Button disconnect
- Button switch wallet network
- Button Update lock
- Button lock ocean
- Button withdraw locked ocean

Most of them can be removed, the remaining ones need to be renamed.

**Comment by trentmc** [comment]
I don't know much about this. @jamiehewitt15 maybe you can help me. 
- what's "Plausible"?
- is this issue still relevant? (Or can I close it)

**Comment by jamiehewitt15** [comment]
Plausible was the analytics service that we used before swapping to posthog. 

This task is done already
