### ISSUE TITLE
Update basic yield metrics: rewardsAmt

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#535]
Based on the following discussions:
https://github.com/oceanprotocol/team-sailfish/issues/22

### DoD:
- [ ] Update nftinfo table to report rewardsAmt

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
