### ISSUE TITLE
Display double allocation if the connected wallet is owner

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/df-web#539]
- [ ] Display double APY if the connect walled is owner (current round & previous rounds => min(125.00, apy * 2)

**note, this is not a separate column, but the values throughout the app wherever the 2x bonus applies need to be accounted for.**
------ comments --------

Probably best if we work through an example on this but it's not always as simple as just *2 because we have a fixed maximum reward that is dispersed for each asset. We should also consider the effect on the APY for the users who are not publishers as this is a zero-sum game, while the publishers get more rewards everyone else gets less.

The simplest example to explain this is when the only person to stake on the asset is the publisher:

stake = 1000
consume volume = 1000
total rewards = 1 (0.1% of DCV)
APY = 0.1%
Publisher APY = 0.1%

If we doubled the APY in the UI and showed the publisher 0.2%, that would be wrong.

To show the impact on other active stakers, consider the following example:

publisher actual stake = 500
publisher effective stake = 1000 (500*2)
non-publisher stake = 500
consume volume = 1000
total rewards = 1 (0.1% of DCV)
Publisher reward = 0.666
non-publisher reward = 0.333

The publisher receives 2/3 of the rewards as their stake has increased but the non-publisher only receives 1/3. The APY goes up for the publisher but down for the non-publisher

------

TODO: 

- [x] have a discussion around this case and figure it out
- [ ] implement into df-web

**Comment by idiom-bytes** [comment]
@EnzoVezzaro let's just make sure allocation value is adjusted.

Let's not address the APY as part of this update.

**Comment by KatunaNorbert** [comment]
@idiom-bytes the `ownerAllocation` column should contain the 2x-ed allocation so the only thing left here is the APY

**Comment by EnzoVezzaro** [comment]
> @idiom-bytes the `ownerAllocation` column should contain the 2x-ed allocation so the only thing left here is the APY

can we close this? I kind of confuse now 🤔

**Comment by KatunaNorbert** [comment]
Me too. I mean the title it's about allocation but the description contains the APY update.

**Comment by jamiehewitt15** [comment]
Yeah, closing this. We can reopen if needed at any point
