### ISSUE TITLE
First-time users see "Connect Wallet" too abruptly

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#559]
### Problem:
We are currently putting the "Connect Wallet" Dialog as the first-action for the user to take, as soon as they connect to the page. Although straight to the point, we might want to revise this.

### Potential Solutions:
Cand A - Keep as is. It's fine.
Cand B - Remove dialog and make it contextual for when the user HAS to connect (such as in the veOCEAN page).
Cand C - Keep dialog and improve the presentation by making it friendlier/more welcoming.

### DoD:
- [ ] Agree on candidate solution
- [ ] Come up with a couple mocks
- [ ] Develop component
- [ ] Review/Sign off

**Comment by KatunaNorbert** [comment]
Fixed, no more Connect Wallet popup opening automatically when app is open
