### ISSUE TITLE
Implement Challenge DF - Dupe

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#576]

**Comment by idiom-bytes** [comment]
This was originally aimed at df.oceandao.org

There might be more adjustments needed than what's covered in here such as including DF Challenges. Lots of feedback, reviews around Data Flows, and other active discussions.  WIP

**Comment by idiom-bytes** [comment]
I updated the epic to split this into 2 parts.
- DF Challenge
- Predictoor

This epic will therefore cover both, in order to deliver both "Active Rewards substreams".
