### ISSUE TITLE
Implement "Challenges" Page

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#582]
### DoD: Challenge page has been built and integrated
- [x] Challenge page is up and running
- [x] "Active Challenge" card is shown and links to predict-eth repo
- [x] predict-eth repo has a `df-challenge.md` or similar file that is fixed/constant
- [x] There is a "Past Challenges" card that has a table of recent winners
- [x] Table of winners include top 3 prizes, and links to each user on etherscan
- [ ] Table retrieves results from df-sql and serves it under "Past Challenges"
- [ ] Rewards page links to "Challenge" page
- [ ] Other source-links point to the "Challenge" page (such as oceanprotocol.com)

**Comment by idiom-bytes** [comment]
It would be constructive if df-sql provided a list of historical epochs, in addition to information about future ones, such as:
- deadline
- total prize
- prize_1
- prize_2
- prize_3

```
epochs = [
  {
    index: 1
    deadline: '15 Jun 2023',
    prize: 2500,
    prize_1: 1250,
    prize_2: 750,
    prize_3: 500,
    winner_1: 0xaaaa,
    winner_2: 0xbbbb,
    winner_3: 0xcccc,
  },
  {
    index: 2
    deadline: '22 Jun 2023',
    prize: 2500,
    prize_1: 1250,
    prize_2: 750,
    prize_3: 500,
    winner_1: 0xaaaa,
    winner_2: 0xbbbb,
    winner_3: 0xcccc,
  }
]
```

**Comment by KatunaNorbert** [comment]
Regarding the actual page I propose some updates:

- make it visual that rewards are distributed to the top 3 results and the rewards available for each place.
- add challenge name to the table, for now we have Predict-ETH challenge but we might have different challenge in the future.
- link each past challenge to the github repo containing the description file so user can see more description about past challenges
- add different name for Predict ETH challenges, having the same name for all it's pretty confusing, so I suggest maybe connecting the name to the epoch, or incrementing number, so as ex Predict ETH 4

**Comment by idiom-bytes** [comment]
```As @idiom-bytes mentioned I'll push towards with moving the epochs.json to df-sql or a common repo, so each project can use it as a source truth.```

Katuna, I reflected on this, and we already have plans for it. Let's keep supporting it this way until we have to restructure.

**Comment by idiom-bytes** [comment]
```
- add challenge name to the table, for now we have Predict-ETH challenge but we might have different challenge in the future.
- link each past challenge to the github repo containing the description file so user can see more description about past challenges
- add different name for Predict ETH challenges, having the same name for all it's pretty confusing, so I suggest maybe connecting the name to the epoch, or incrementing number, so as ex Predict ETH 4
```

These are not requirements set by trent.
1. There will only be 1 file. challenge-df
2. Please see 1. Data Challenges are S2.
3. Please see 1. Less overhead. Button/main CTA links to it. Less confusion/leaky bucket.
4. Please see 1.

**Comment by idiom-bytes** [comment]
```
I agree with us better structuring the available rewards inside epochs, then we could reduce the overall number of endpoints. Based on the epochs structure provided above, I think we can move the available rewards part into current epochs.json structure and the winners into the rewards endpoint, so no new endpoint it's added with possible duplicated info.
```

Let's merge this with the streams update. I believe it will get handled relatively clean.
