### ISSUE TITLE
Use DF round number for challenge DF table.

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#593]
As discussed:
- [x] Table will point to the DF rounds
- [x] Table will show winners
- [x] There will not be a challenge name
- [x] The only name visible will be ChallengeDF
- [x] Prizes for upcoming ChallengeDF are coming from epochs.json
- [x] Epochs.json contains prizes for upcoming ChallengeDF rounds
- [x] Updated HistoricCard.svelte to proprely subscribe/unsubscribe from svelte store

**Comment by idiom-bytes** [comment]
For posterity: ```
This is now mocked, but, we should define a source for active Predict-ETH challenge. I see 2 options here:
- because the name of the challenge it's going to stay the same and so will the other parameters, simply just get the round number based on last round number.
- define an active Predict-ETH json which contains all the updated data and composed somewhere in the BE, maybe inside epochs.json and simply read the data from there.
```
