### ISSUE TITLE
Display claimable rewards broken down by stream

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#599]
In order to complete this we may need:
- [ ] To know when the user claimed last active rewards relative to distributions (passive contract)
- [ ] To know when the user claimed last passive rewards relative to distributions (active contract)
- [ ] To know how much the user earned per stream per round
- [ ] We can then break down the claimable amount based on each stream

**Comment by idiom-bytes** [comment]
Use subgraph query to find passive claims collected by an individual;
**Goal:**  You can get the amount available to claim from the contract
Metrics - You can find out how much they have claimed in the past
Metrics - You can also get the count of how many times they claimed
```
{
  veOCEANs(first: 100) {
    id
    lockedAmount
    claims {
      id
      amount
      claim_epoch
      timestamp
    }
  }
}
```

Use subgraph query to find rewards distributed over time vs. what's available left over to claim
**Goal:**  You can get however much is available to claim from the query
Metrics - You can also find out how many times they have earned the reward
Metrics - We can then (1) find out how much they can claim (2) find out how much they won per round, (3) find out how much they won via challenges (4) report the amount available, or winnings per stream
```
{
  dfrewards(first: 100) {
    id
    receiver {
      id
    }
    availableClaims {
      id
      receiver {
        id
      }
      amount
    }
    history {
      id
      receiver {
        id
      }
      amount
      timestamp
    }
  }
}
```

**Comment by idiom-bytes** [comment]
Updated the design for the rewards page, proposing the following hierarcy:
1. Total rewards per stream
2. Total rewards per substream
3. Claimable rewards per substream
4. Total Claimable rewards per stream
5. Historical Rewards per stream (**we should potentially omit this** and save it for a different area/card/insights - _I believe our previous designs for historical rewards should focus on addressing this_). 

This can be more easily viewed here
![image](https://github.com/oceanprotocol/df-web/assets/69865342/70788494-dc85-4d02-a698-a1ac8f831dcc)

**Comment by KatunaNorbert** [comment]
@idiom-bytes Nice research and great issue description, thanks for the details and suggestions.

I suggest no having the Lifetime Rewards for now, it's seems a little bit off.
