### ISSUE TITLE
[APY calc v1] Improve comms around APY calc

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#610]
### Problem:
There still isn't a complete description of APY calc in app. Place it somewhere.

### Outline:
Provide tooltip-description of APY calc and what goes into it.
**DRY - This should exist in 1 clear location and not be duplicated around.**

```
APY assumes a 4-year lock up period with a weekly schedule of compounding rewards into an updated 4-year lock. This estimate is calculated assuming the current numbers remain constant: number of users, reward emissions, other parameters, while excluding all tx fees [You can verify the calculation here](https://github.com/oceanprotocol/df-web/blob/f05c69fe80751aeeb167a61fe0cd690e125ad245/src/utils/rewards.js)
```

### DoD:
- [ ] APY calc comms is DRY and visible somewhere via a tooltip/fine print

**Comment by KatunaNorbert** [comment]
This is closely related to #610, and we should bundle them together. If we want to add info around APY we should first add the actual value
