### ISSUE TITLE
3 boxes in "Rewards" section are useless, recommend deleting them. Also delete "Reward Programs" mid-title

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#633]
### Background / motivation

If you go to df.oceandao.org then it will auto-redirect to df.oceandao.org/rewards.

Screenshot:
![rewards](https://github.com/oceanprotocol/df-web/assets/5305452/11787f06-2c58-4583-a21b-97e0d864ced2)

**Information architecture of the page:**
1. Key top-level info: round number, OCEAN available, avg APY, (your APY if connected), time to next rewards. 
2. Three "benefits" boxes: "veOCEAN: .. battle-tested contracts ..", "Weekly Rewards: .. run weekly ..", "For everyone: numerous participants can benefit"
3. Detail info for each DF stream: Passive, Active: {Volume, Challenge}. For each stream, rewards available, (your rewards if connected), (claim rewards if connected) 

### Background / motivation 2

We now have pretty good DF docs, at https://docs.oceanprotocol.com/rewards 

Screenshot:
![docs](https://github.com/oceanprotocol/df-web/assets/5305452/1f69725a-e8b0-4e75-8df7-b2f1c5ebe930)

These docs are linked directly from the "about" button. 

### Background / motivation 3

There's now a "Data Farming" hub page directly from oceanprotocol.com site, specifically at https://oceanprotocol.com/earn/data-farming. It got shipped recently, on approx Aug 14, 2023.

Screenshot:
![hub](https://github.com/oceanprotocol/df-web/assets/5305452/dba7fb73-e5c0-4dcf-a798-9aff6a7e7476)

FYI it isn't perfect yet: it's missing the "Challenge DF" substream and more. But @idiom-bytes is on top of that, via specific issues in "site" repo.

### On the three "benefits" boxes 

- They're there to teach benefits of Data Farming. But the page shouldn't really have to do that, and in trying to do so clutters up the page unnecessarily
- The content inside the "benefits" boxes is not helpful: 
  - "veOCEAN": "battle-tested contract" is way down on the list of benefits of veOCEAN
  - "Weekly rewards": simpler is to add "Weekly" before "Round" in the "key top-level info" section. Don't need a whole box
  - "For everyone": waste of space, there is zero information in this box
-  We now have two other places that explains benefits : (a) DF Hub to onboard people for the first time, and (b) docs for more details yet

Summary: benefits boxes are redundant, with not-so-useful information that clutters up the "Rewards" page

### On "Reward Programs" mid-title

Right below the "benefits" boxes and above the Detail info for each DF stream, there's a mid-title that says "Reward Programs"

Problem: It doesn't really add any useful info.

### Recommended TODOs

- [x] Remove the "benefits boxes"
- [x] Remove "Rewards Programs" mid-title

**Comment by KatunaNorbert** [comment]
Oh, didn't know about this page inside the website.

The purpose of those boxes was: 
-to serve a presentation purpose for users who land on the page for the first time. Useful when we don't have a presentation page like the recent one from website.
-give a feedback and guidance by showing more advanced futures base on the state of the user's connected wallet ( If already locked we don't show lock related information rather highlight what possibilities it has after that ).

Now that we have the website update we can iterate on this component

**Comment by trentmc** [comment]
> Now that we have the website update we can iterate on this component

I think we can remove it. Especially if we have a one-sentence summary at the top.
