### ISSUE TITLE
Add Predictoor substream

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#634]
Df-web needs to be updated and have a new substream for Predictoor. 

All data needed for Predictoor component exists inside of df-sql. We'll display what's possible, and a brief summary.
- Do not add Oasis network/claiming from df-web
- Point the user to `pdr-backend` readme
- The following can be built using data that will exist in df-sql (predictoorData + predictoorSummary)

![image](https://github.com/oceanprotocol/df-web/assets/69865342/11be76a5-c188-4351-b5e1-bf87281e6e0d)

**Comment by KatunaNorbert** [comment]
Issues:
- Can't get the rewards amount. To get the rewards amount from the contract, each epoch has to be queried which it's not reliable from the UI. We could get rewards from df-sql but that data doesn't take in consideration the previous claimed amount. We are investigating to see if there is a solution for this.

**Comment by idiom-bytes** [comment]
Yeah we can. You are mixing up [contract-level] rewards for [predictoor-df] rewards.

### [Predictoor contract-level rewards]
t3.sol slashing/rewards for submitting correct predictions will be available inside each t3.sol that is deployed. these rewards exist naturally as a result of t3.sol and are available in the contract and come from:
- competing in predictions (stake slashing/rewarding)
- buying subscriptions (value is distributed over future epochs)

Therefore:
1. predictoors **will claim the t3 contract-level rewards from pdr-backend**
1. there are no requirements for us to implement this in the FE

### [Weekly predictoor-df rewards]
- these rewards are being calculated inside of df-py and are available inside df-sql
- these rewards are claimable from df-web, with a single tx, on ethereum mainnet
- these rewards are distributed to DFRewards.sol
- these rewards (and whether they are claimable or not) are available from df-sql just like everything else we're doing up-to-now
```
const predictoorSummary = `CREATE TABLE predictoor_summary(
    chainID                     INT NOT NULL,
    predictoor_addr             VARCHAR(42) NOT NULL,
    contract_addr               VARCHAR(42) NOT NULL,
    prediction_count            INT NOT NULL,
    correct_prediction_count    INT NOT NULL,
    accuracy                    FLOAT(94, 10) NOT NULL,
    round                       INT NOT NULL,
    PRIMARY KEY(chainID, predictoor_addr, contract_addr, round)
```

The following design should work for what we need inside of DF-web
![image](https://github.com/oceanprotocol/df-web/assets/69865342/4a120a04-b5ab-4fc1-b3cd-4bac5e6b573a)

**Comment by trentmc** [comment]
Complete, just don't merge until we go live with Predictoor DF

**Comment by KatunaNorbert** [comment]
To do before merge:
- [ ] update blogpost link from Bannner to released Predictoor-DF blogpost
