### ISSUE TITLE
In DF History table, each round" and "start date" has duplicate entries 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#642]
it was chrome on ios

See bottom left of image below.

![IMG_4018](https://github.com/oceanprotocol/df-web/assets/5305452/a8df13ed-3e54-49bd-b0ff-f154d6ef7663)

**Comment by KatunaNorbert** [comment]
Just checked and looks good on my end. Does it still occur?

**Comment by trentmc** [comment]
I can't reproduce it on my phone right now

So I guess we can close it. 

If the issue recurs, I'll reopen, or do a new issue
