### ISSUE TITLE
Hook DF T&C to UI

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#649]
### Problem
Terms and conditions are not hooked to the UI. 

Terms should likely remain visible in NAV bar rather than inside Volume DF page as to remain clearly visible.

### DoD:
- [ ] Terms and Conditions are clearly visible on the website and easy to navigate to

### Related

- write T&C: DF: https://github.com/oceanprotocol/df-web/issues/648
- write & publish T & C: Predictoor: https://github.com/oceanprotocol/pdr-private/issues/42

**Comment by KatunaNorbert** [comment]
@trentmc @idiom-bytes @trizin  I suggest, that for Terms of use agreement inside DF website to use the already existent checkbox connected to lock ocean button, and mention the terms there:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGRRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02848d9cf4f2773f453204bb73261c0f0bb933bc/Screenshot%202023-10-19%20at%2010.56.45.png)

**Comment by trentmc** [comment]
OK with me
