### ISSUE TITLE
In df.oceandao.org/volume-df, for predictoor assets, make "↗" link to the data_nft's url on etherscan

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#669]
This issue was motivated by "Add timeframe to Predictoor Assets name" [df-py#742](https://github.com/oceanprotocol/df-py/issues/742) with description:

> Right now it's hard to differentiate on the df-web side which is a 1h timeframe and which is a 1d timeframe asset. They are looking exactly the same.
> I propose we also add the timeframe to the asset name so we know what's the difference. [that name propagates to csv, and on to df-web]

That issue is a WIP. 

There's a complementary thing for df-web: in make the "↗" in df.oceandao.org/volume-df link to the data_nft's url on etherscan. It would be extremely helpful.

Details: Right now the "↗" arrow goes to predictoor.ai generally. But that's not so helpful to get extra information about the asset, because you still can't distinguish among the 20 feeds. For non-predictoor asset it goes to the asset listing in Ocean Market, with data nft address and more.

**Comment by KatunaNorbert** [comment]
Makes sense. I think the logic behind linking to Predictoor website is to be consistent with the other assets, where we link to the dapp where there are displayed and can be bought(Marketplace). But I see your point, Pdr-web doesn't give specific information on for asset
