### ISSUE TITLE
Predictoor DF page

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#698]
@idiom-bytes comments on removing Challenge-DF:

I reviewed the PR and it looks good.

I also tried to further remove stuff from terms.md, EpochHistory.svelte, and rewards.js, however I decided to leave those there.

I do think that ChallengeDF has sunset and we want users to focus on what's next (becoming a predictoor) and that is now somewhat missing.

The banner are for announcements/new things
The rewards page, only have 1 line and 1 button to take you to predictoor
<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7013ce34f04d560582dcab77efb3ee50a570f5c0/290251526-11b982bb-b3e8-41bc-ac51-68c4976bd795.png" alt="290251526-11b982bb-b3e8-41bc-ac51-68c4976bd795.png" />

Therefore, although this PR looks good, I think we lost a good amount of visibility/prevalence towards the reward program. I.E. How can we perhaps make predictoor rewards more prevalent?

Forward looking recommendation
@KatunaNorbert @trentmc

My suggestion therefore is to:

Merge this PR
Design how to make predictoor rewards more visible/prevalent
Suggestions for how to solve (2)

Add a page for Predictoor DF similar to what Challenge DF looked like
Predictoor DF page can emphasize a bit more what it's all about + link to predictoor.ai
Sunset the Predictoor DF banner for a more permanent solution
<img width="889" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUZlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45227c81e42a2611261a3a6d0082c6b4893f5ed3/290253288-ad2f877d-63a6-44c8-8c3d-f9adcdf6cdf0.png" alt="290253288-ad2f877d-63a6-44c8-8c3d-f9adcdf6cdf0.png" />

**Comment by trentmc** [comment]
Done
