### ISSUE TITLE
Data Farming Chain

### ISSUE THREAD

**Issue by Pfed-prog** [oceanprotocol/df-web#715]
**Describe the bug**
 
_Could not find a better repository._

Connecting to the Page and not seeing the data because not on the right network.

**To Reproduce**

https://df.oceandao.org/rewards

Use any network other than mainnet ethereum

**Expected behavior**

Not Displaying any data or querying ethereum mainnet irrespective of the users chain in metamask.

On wrong Chain

<img width="1082" alt="image" src="https://github.com/oceanprotocol/docs/assets/66903336/7e9b07ad-5f48-4648-9801-f5d836c27fa6">

On Ethereum Mainnet

<img width="1004" alt="image" src="https://github.com/oceanprotocol/docs/assets/66903336/da984546-3f41-4576-833e-0993539a96ff">

**Comment by trentmc** [comment]
cc @KatunaNorbert . This was reported by a user in the docs/ repo. df-web is the more appropriate user, so I moved it here.

**Comment by KatunaNorbert** [comment]
Thanks @trentmc for creating this ticket. I managed to reproduce the issue, basically the rewards are not cleared and set to 0 when switching to another network that is not supported, but all the other values are cleared and buttons are disabled.
Not high priority issue but I will handle it soon.
