### ISSUE TITLE
Console Logs - Clean them + Implement log level

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#86]
There are a ton of console logs that I added as I implemented things.
We probably want to simplify them while maintaining them to some degree

We may want to Implement log level for debugging/shipping purposes

### DoD:
- [ ] Console logs have been simplified/consolidated (i.e. 1 log, all parameters, at top of functions).
- [ ] Console logs can be disabled via log levels
- [ ] Switching log level can be done easily from one place (i.e. app.config.js / app.svelte)

**Comment by trentmc** [comment]
Given Predictoor, DF Challenge, DF Predictoor: this is super-low priority, and will look different when revisited. And we have _way_ too many issues. So closing this.
